# Generated by Django 5.1.1 on 2025-05-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedhotels',
            name='count',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
